# RuboCop configuration for Undertake HQ Ruby projects
# Projects can inherit from this configuration using:
#
# inherit_gem:
#   undertakehq-ruby-standards: config/rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

# Layout
Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#'  # Allow long comments

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics
Metrics/MethodLength:
  Max: 25
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Max: 25
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'Rakefile'
    - '*.gemspec'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/ClassLength:
  Max: 200
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/ModuleLength:
  Max: 200
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/AbcSize:
  Max: 20
  CountRepeatedAttributes: false

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 10

# Style
Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/Documentation:
  Enabled: true
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: either

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: predicate

# Naming
Naming/VariableNumber:
  EnforcedStyle: normalcase

Naming/PredicatePrefix:
  ForbiddenPrefixes:
    - is_
  AllowedMethods:
    - is_a?

# Lint
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Lint/MissingSuper:
  Enabled: false

# Security
Security/YAMLLoad:
  Enabled: true
